## ================================================================================================================================
## base env setup
## ================================================================================================================================
# 服务端口号
server.port=${SERVER_PORT:9988}
## ================================================================================================================================
## spring actuator setup
## ================================================================================================================================
# 将自己注册到监控平台
spring.boot.admin.notify.pagerduty.client-url=${ADMIN_NOTIFY_PAGERDUTY_CLIENT_URL:http://localhost:9988}
spring.boot.admin.notify.pagerduty.enabled=${ADMIN_NOTIFY_ENABLED:true}